# Generated by Django 4.2.5 on 2024-03-18 13:08

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_area', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_fee', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media')),
                ('cover_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media')),
                ('business_code', models.CharField(blank=True, default='ABC', max_length=255, null=True)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_address', models.CharField(blank=True, max_length=255, null=True)),
                ('business_location', models.CharField(blank=True, max_length=255, null=True)),
                ('business_slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('business_contacts', models.CharField(blank=True, max_length=255, null=True)),
                ('about_business', models.TextField(blank=True, max_length=255, null=True)),
                ('business_seo', models.TextField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_owner', to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='My_Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Counter', 'Counter'), ('Waiter', 'Waiter'), ('User', 'User')], default='Admin', max_length=255)),
                ('active_status', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='business.businessprofile')),
                ('business_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_user', to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Location_occupied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupied', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('location_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_space', to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('location_type', models.CharField(choices=[('Admin', 'Admin'), ('Other', 'Other')], default='Admin', max_length=255)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('business_l', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_l', to='business.businessprofile')),
                ('l_added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='l_added_by', to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('role_1', models.BooleanField(default=False)),
                ('role_2', models.BooleanField(default=False)),
                ('role_3', models.BooleanField(default=False)),
                ('role_4', models.BooleanField(default=False)),
                ('role_5', models.BooleanField(default=False)),
                ('role_6', models.BooleanField(default=False)),
                ('role_7', models.BooleanField(default=False)),
                ('role_8', models.BooleanField(default=False)),
                ('active_status', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('e_added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_added_by', to='account.profile')),
                ('e_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_business', to='business.businessprofile')),
                ('employees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Business_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Counter', 'Counter'), ('Waiter', 'Waiter'), ('User', 'User')], default='Admin', max_length=255)),
                ('counter_order_time', models.IntegerField(default=1)),
                ('products', models.BooleanField(default=False)),
                ('restaurant', models.BooleanField(default=False)),
                ('rooms', models.BooleanField(default=False)),
                ('other_services', models.BooleanField(default=False)),
                ('chat', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('s_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_business', to='business.businessprofile')),
                ('set_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_by', to='account.profile')),
            ],
        ),
    ]
