# Generated by Django 4.2.5 on 2024-03-18 13:08

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarCounterStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_no', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to='account.profile')),
                ('stock_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_owner', to='business.businessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DrinksCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('bar_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_cat', to='business.businessprofile')),
                ('category_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_by', to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='DrinksItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('presentation', models.CharField(blank=True, max_length=255, null=True)),
                ('new_price', models.DecimalField(decimal_places=1, default=0.0, max_digits=25)),
                ('old_price', models.DecimalField(decimal_places=1, default=0.0, max_digits=25)),
                ('cover_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media')),
                ('availability', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('ingridients', models.TextField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('minimum_stock_level', models.PositiveIntegerField(default=0)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.IntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=1, default=0, max_digits=25)),
                ('shipping_fee', models.DecimalField(decimal_places=1, default=0, max_digits=25)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('payement_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('paid', models.CharField(blank=True, max_length=255, null=True)),
                ('balance', models.CharField(blank=True, max_length=255, null=True)),
                ('order_note', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('source', models.CharField(default='None', max_length=255)),
                ('order_status', models.CharField(choices=[('Placed', 'Placed'), ('Packed', 'Packed'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Order Placed', max_length=255)),
                ('payement_status', models.CharField(choices=[('Pay On Delivery', 'Pay On Delivery'), ('Pay Before Delivery', 'Pay Before Delivery')], default='Not Paid', max_length=255)),
                ('code_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_address', to='business.location')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='account.profile')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivered_by', to='account.profile')),
                ('order_s_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_s_by', to='account.profile')),
                ('order_summary_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_summary_business', to='business.businessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.drinksitems')),
                ('purchase_order_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_by', to='business.businessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_order_no', models.IntegerField(default=0)),
                ('order_note', models.TextField(blank=True, null=True)),
                ('delivery_address', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_contacts', models.CharField(blank=True, max_length=255, null=True)),
                ('shipper_status', models.BooleanField(default=False)),
                ('client_status', models.BooleanField(default=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('note_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_by', to='account.profile')),
                ('order_summary_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_summary_note', to='bar.order_summary')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Payement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payement_type', models.CharField(choices=[('Not Paid', 'Not Paid'), ('Cash', 'Cash'), ('Mobile Money', 'Mobile Money'), ('Merchant', 'Merchant'), ('Credit/Debt Card', 'Credit/Debt Card'), ('Mobile Money and Cash', 'Mobile Money and Cash'), ('Bank', 'Bank'), ('E-Transfer', 'E-Transfer')], default='Not Paid', max_length=255)),
                ('payement_mode', models.CharField(choices=[('Pay On Delivery', 'Pay On Delivery'), ('Pay Before Delivery', 'Pay Before Delivery')], default='Not Paid', max_length=255)),
                ('card_or_merchant_no', models.CharField(blank=True, max_length=255, null=True)),
                ('recieved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('purpose', models.CharField(choices=[('Order', 'Order'), ('Shipping', 'Shipping'), ('Additional Fees', 'Additional Fees'), ('Others', 'Others')], default='Order', max_length=255)),
                ('amount_paid', models.DecimalField(decimal_places=1, default=0, max_digits=25)),
                ('balance', models.DecimalField(decimal_places=1, default=0, max_digits=25)),
                ('seller_status', models.BooleanField(default=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('payed_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payed_order', to='bar.order_summary')),
            ],
        ),
        migrations.CreateModel(
            name='DrinksSubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='bar.drinkscategories')),
            ],
        ),
        migrations.AddField(
            model_name='drinksitems',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='bar.drinkssubcategories'),
        ),
        migrations.CreateModel(
            name='CloseOpenStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateField()),
                ('open_and_closed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_and_closed_by', to='business.businessprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.drinksitems')),
            ],
        ),
        migrations.CreateModel(
            name='CartOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='None', max_length=255)),
                ('product_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media')),
                ('quantity', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=1, default=0, max_digits=25)),
                ('total_price', models.DecimalField(decimal_places=1, default=0, max_digits=25)),
                ('total_order_price', models.DecimalField(decimal_places=1, default=0, max_digits=25)),
                ('amount_paid', models.DecimalField(decimal_places=1, default=0, max_digits=25)),
                ('balance', models.DecimalField(decimal_places=1, default=0, max_digits=25)),
                ('source', models.CharField(default='None', max_length=255)),
                ('buyer_status', models.BooleanField(default=False)),
                ('seller_status', models.BooleanField(default=False)),
                ('recieved_status', models.BooleanField(default=False)),
                ('order_no', models.IntegerField(default=0)),
                ('order_payement_mode', models.CharField(choices=[('Not Paid', 'Not Paid'), ('Cash', 'Cash'), ('Mobile Money', 'Mobile Money'), ('Merchant', 'Merchant'), ('Credit/Debt Card', 'Credit/Debt Card'), ('Mobile Money and Cash', 'Mobile Money and Cash'), ('Bank', 'Bank'), ('E-Transfer', 'E-Transfer')], default='Not Paid', max_length=255)),
                ('order_transaction_id', models.CharField(default='None', max_length=255)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('order_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_by', to='account.profile')),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='bar.drinksitems')),
                ('worked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worked_by', to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='BarItemStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.PositiveIntegerField(default=0)),
                ('damaged', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_damage_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity_on_hand', models.PositiveIntegerField(default=0)),
                ('purchase_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity_stocked', models.PositiveIntegerField()),
                ('bar_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.drinksitems')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='bar.barcounterstock')),
                ('stock_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_by', to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='BarInventoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_stocked_at_hand', models.PositiveIntegerField(default=0)),
                ('damaged', models.PositiveIntegerField(default=0)),
                ('good', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='bar.drinksitems')),
            ],
        ),
    ]
